name: Keep Render Service Awake

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes now
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /chat endpoint
        run: |
          curl -X POST https://my-chatbot.onrender.com/chat \
               -H "Content-Type: application/json" \
               -d '{"message":"hi"}' \
               --silent --show-error --fail

      
