name: Ping Portfolio Chatbot Health

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes (UTC)
  workflow_dispatch:  # Optional manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Just hit the health endpoint
        run: curl https://portfoliochatbot-h3zm.onrender.com/health
